### PR TITLE
Add electron packager support

### PR DESCRIPTION
**Pull request by erikyuzwa**
- Added a screenshot for the project
- Added support for creating Electron builds to distribute your JSRL project
- Updated README notes

### CODE REVIEW

**Comment by erikyuzwa** [comment]
I don't know if you want something like this in the base repo @slashman ? Maybe it stay as a pull request available to whoever might want to use it with the JSRL?

**Comment by slashman** [comment]
This is definitively something I'd want to have in. I have to check back and see why we didn't merge it.

**Comment by erikyuzwa** [comment]
thanks. The only thing "missing" (IMHO) is the ability to hot-reload an Electron window running your project. I can look into that if you think that would be a key missing link here..

**Comment by erikyuzwa** [comment]
won't delete this, but closing in favor of https://github.com/slashman/jsrl/pull/3

**Pull request closed without merging**
